[project]
name = "oikotool"
version = "1.2.0"
description = "Command-line tool to automate property searches on Oikotie.fi"
authors = [{ name = "Janne K", email = "hi@jakan0.dev" }]
license = { text = "MIT" }
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
    "tenacity>=9.0.0",
    "typer>=0.12.5",
]

[project.scripts]
oikotool = "oikotool.cli:main"

[dependency-groups]
dev = [
    "mypy>=1.11.2",
    "pytest>=8.3.2",
    "ruff>=0.5.7",
    "types-beautifulsoup4>=4.12.0.20240511",
    "types-requests>=2.32.0.20240712",
]

[tool.hatch.build.targets.sdist]
only-include = ["src", "tests"]

[tool.hatch.build.targets.wheel]
packages = ["src/oikotool"]

[tool.mypy]
allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_missing_imports = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
cache-dir = "~/.cache/ruff"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["oikotool"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
