name: Publish Oikotool

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Ruff linter
        run: poetry run ruff check .

      - name: Run Ruff formatter
        run: poetry run ruff format --check .

      - name: Run mypy static type checker
        run: poetry run mypy .

      - name: Run tests
        run: poetry run pytest -vv

      - name: Build project
        run: poetry build

      - name: Get wheel filename
        id: filename
        run: echo "WHEEL=$(ls dist/*.whl)" >> "${GITHUB_OUTPUT}"

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.filename.outputs.WHEEL }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
